version: "3"
services:
  update_metadata_loop:
    build: .
    env_file:
      - .env
    command: rake update_metadata_loop
  gen_data_loop:
    build: .
    env_file:
      - .env
    command: rake gen_data_loop
    volumes:
      - ~/data:/usr/src/app/data
  update_goerli_pangolin2_messages:
    build: .
    env_file:
      - .env
    command: rake update_goerli_pangolin2_messages
  update_pangolin2_goerli_messages:
    build: .
    env_file:
      - .env
    command: rake update_pangolin2_goerli_messages
  server:
    build: .
    env_file:
      - .env
    command: ruby src/server.rb
    ports:
      - "4567:4567"
    volumes:
      - ~/data:/usr/src/app/data
