version: "3"
services:
  update_metadata:
    build: .
    env_file:
      - .env
    command: rake update_metadata_loop
  gen_supplies_data:
    build: .
    env_file:
      - .env
    command: rake gen_supplies_data_loop
    volumes:
      - ./data:/usr/src/app/data
  update_nominees:
    build: .
    env_file:
      - .env
    command: rake update_nominees_loop
    volumes:
      - ./data:/usr/src/app/data
  server:
    build: .
    env_file:
      - .env
    command: ruby src/server.rb
    ports:
      - "4567:4567"
    volumes:
      - ./data:/usr/src/app/data
