version: "3"
services:
  update_metadata_loop:
    build: .
    command: rake update_metadata_loop
  gen_data_loop:
    build: .
    command: rake gen_data_loop
  update_goerli_pangolin2_messages:
    build: .
    environment:
      - GOERLI_ENDPOINT=${GOERLI_ENDPOINT}
      - MONGODB_URI=${MONGODB_URI}
    command: rake update_goerli_pangolin2_messages
  update_pangolin2_goerli_messages:
    build: .
    environment:
      - PANGOLIN_ENDPOINT=${PANGOLIN_ENDPOINT}
      - MONGODB_URI=${MONGODB_URI}
    command: rake update_pangolin2_goerli_messages
  server:
    build: .
    command: ruby server.rb
    ports:
      - "4567:4567"
